# Generated by Django 3.1.2 on 2020-10-29 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_list', models.CharField(max_length=95)),
                ('connect_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.school')),
            ],
        ),
    ]
