# Generated by Django 3.1.2 on 2020-10-20 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_auto_20201020_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_list', models.CharField(max_length=95)),
                ('connect_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school_details')),
            ],
        ),
    ]
