# Generated by Django 3.1.2 on 2020-12-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_temp',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
