# Generated by Django 3.1.2 on 2020-12-22 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_subject_subject_temp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='class_list',
            new_name='class_name',
        ),
    ]
