# Generated by Django 3.1.2 on 2020-12-22 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_roll_num'),
        ('school', '0004_auto_20201222_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_marks', models.IntegerField(null=True)),
                ('pass_marks', models.IntegerField(null=True)),
                ('obtained_marks', models.IntegerField(null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.subjectslist')),
            ],
        ),
    ]
