# Generated by Django 3.1.2 on 2020-12-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_marksreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='marksreport',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
