# Generated by Django 3.1.1 on 2020-09-25 15:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='schoolDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=95)),
                ('subdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=100)),
                ('principal', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='Nepal', max_length=100)),
                ('estdate', models.DateField(default=django.utils.timezone.now)),
                ('numstd', models.IntegerField(default=0)),
                ('url', models.URLField(default='')),
                ('password', models.CharField(max_length=95)),
            ],
        ),
    ]
