# Generated by Django 3.1.2 on 2020-10-29 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=95)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=100)),
                ('principal', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='Nepal', max_length=100)),
                ('established_date', models.CharField(default=django.utils.timezone.now, max_length=95)),
                ('nepali_established_date', models.CharField(default='2077-07-14', max_length=95)),
                ('student_number', models.IntegerField(default=0)),
                ('school_website', models.URLField(default='')),
                ('password', models.CharField(max_length=95)),
                ('user_ip', models.CharField(max_length=95)),
                ('logo', models.ImageField(default='/media/web/your-logo-here.png', max_length=500, upload_to='')),
            ],
        ),
    ]
