# Generated by Django 3.1.1 on 2020-09-26 03:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='school_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=95)),
                ('submitted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=100)),
                ('principal', models.CharField(default='', max_length=150)),
                ('address', models.CharField(default='Nepal', max_length=100)),
                ('established_date', models.DateField(default=django.utils.timezone.now)),
                ('student_number', models.IntegerField(default=0)),
                ('school_website', models.URLField(default='')),
                ('password', models.CharField(max_length=95)),
                ('user_ip', models.CharField(max_length=95)),
            ],
        ),
        migrations.DeleteModel(
            name='schoolDetails',
        ),
    ]
