# Generated by Django 3.1.1 on 2020-09-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200926_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_details',
            name='logo',
            field=models.ImageField(default='/media/web/your-logo-here.png', max_length=500, upload_to=''),
        ),
    ]
