# Generated by Django 3.1.1 on 2020-10-04 17:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_school_details_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='school_details',
            name='nepali_established_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=95),
        ),
    ]
