# Generated by Django 3.1.1 on 2020-10-05 01:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_school_details_nepali_established_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_details',
            name='established_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=95),
        ),
        migrations.AlterField(
            model_name='school_details',
            name='nepali_established_date',
            field=models.CharField(default='2077-06-19', max_length=95),
        ),
    ]
