# Generated by Django 3.1.2 on 2020-10-19 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201018_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school_details',
            name='nepali_established_date',
            field=models.CharField(default='2077-07-03', max_length=95),
        ),
    ]
