# Generated by Django 3.1.2 on 2020-10-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_remove_student_class_ssname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_class',
            old_name='username',
            new_name='connect_school',
        ),
    ]
