# Generated by Django 3.1.2 on 2020-10-20 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20201020_0401'),
        ('settings', '0004_auto_20201016_1113'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student_class',
        ),
    ]
