# Generated by Django 3.1.2 on 2020-10-23 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '__first__'),
        ('accounts', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150, null=True)),
                ('student_short_name', models.CharField(max_length=150, null=True)),
                ('student_address', models.CharField(max_length=150)),
                ('student_father', models.CharField(max_length=150, null=True)),
                ('student_mother', models.CharField(max_length=150, null=True)),
                ('student_fam_occupation', models.CharField(max_length=150, null=True)),
                ('student_phone_number', models.CharField(max_length=95, null=True)),
                ('student_photo', models.ImageField(max_length=500, upload_to='')),
                ('connect_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school_details')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='school.student_class')),
            ],
        ),
    ]
