# Generated by Django 3.1.1 on 2020-09-25 15:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stdClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=95)),
                ('ssname', models.CharField(max_length=95)),
                ('cList', models.CharField(max_length=95)),
            ],
        ),
        migrations.CreateModel(
            name='stdDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=95)),
                ('stname', models.CharField(max_length=150, null=True)),
                ('ssname', models.CharField(max_length=150, null=True)),
                ('stadd', models.CharField(max_length=150)),
                ('stfname', models.CharField(max_length=150, null=True)),
                ('stmname', models.CharField(max_length=150, null=True)),
                ('stfo', models.CharField(max_length=150, null=True)),
                ('stadate', models.DateField(default=django.utils.timezone.now)),
                ('stpnum', models.CharField(max_length=95, null=True)),
                ('stbdate', models.DateField(default=django.utils.timezone.now)),
                ('stpht', models.ImageField(max_length=500, upload_to='')),
                ('stcls', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.stdclass')),
            ],
        ),
    ]
