# Generated by Django 3.1.2 on 2020-10-29 12:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '__first__'),
        ('school', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
                ('gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], default='1', max_length=9)),
                ('ethnicity', models.CharField(choices=[('brah', 'Brahmin'), ('cht', 'Chhetri'), ('jj', 'Janajati'), ('dl', 'Dalit'), ('md', 'Madhesi')], default='1', max_length=9)),
                ('short_name', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=150)),
                ('father', models.CharField(max_length=150, null=True)),
                ('mother', models.CharField(max_length=150, null=True)),
                ('fam_occupation', models.CharField(max_length=150, null=True)),
                ('nepali_admission_date', models.CharField(default='2077-07-13', max_length=150, null=True)),
                ('eng_admission_date', models.CharField(default=django.utils.timezone.now, max_length=150, null=True)),
                ('admission_date', models.DateField(default=django.utils.timezone.now, max_length=150, null=True)),
                ('nepali_dob_date', models.CharField(default='2077-07-13', max_length=150, null=True)),
                ('eng_dob_date', models.CharField(default=django.utils.timezone.now, max_length=150, null=True)),
                ('dob_date', models.DateField(default=django.utils.timezone.now, max_length=150, null=True)),
                ('phone_number', models.CharField(max_length=95, null=True)),
                ('photo', models.ImageField(default='/media/web/', max_length=500, upload_to='')),
                ('Class', models.ForeignKey(default='Null Class', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='school.class')),
                ('connect_school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school')),
            ],
        ),
    ]
