# Generated by Django 3.1.1 on 2020-09-26 03:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=95)),
                ('student_name', models.CharField(max_length=150, null=True)),
                ('student_short_name', models.CharField(max_length=150, null=True)),
                ('student_address', models.CharField(max_length=150)),
                ('student_father', models.CharField(max_length=150, null=True)),
                ('student_mother', models.CharField(max_length=150, null=True)),
                ('student_fam_occupation', models.CharField(max_length=150, null=True)),
                ('stadate', models.DateField(default=django.utils.timezone.now)),
                ('student_phone_number', models.CharField(max_length=95, null=True)),
                ('student_date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('student_photo', models.ImageField(max_length=500, upload_to='')),
                ('student_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.student_class')),
            ],
        ),
        migrations.RemoveField(
            model_name='stddetails',
            name='stcls',
        ),
        migrations.DeleteModel(
            name='stdClass',
        ),
        migrations.DeleteModel(
            name='stdDetails',
        ),
    ]
