# Generated by Django 3.1.2 on 2020-12-22 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='roll_num',
        ),
    ]
