# Generated by Django 3.1.2 on 2020-10-27 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='dob_date',
            field=models.DateField(default=django.utils.timezone.now, max_length=150, null=True),
        ),
    ]
