# Generated by Django 3.1.2 on 2020-10-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_details',
            name='student_fam_occupation',
            field=models.CharField(default='Studying', max_length=150, null=True),
        ),
    ]
