# Generated by Django 3.1.1 on 2020-10-01 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_school_details_logo'),
        ('student', '0002_auto_20200926_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='password',
        ),
        migrations.AlterField(
            model_name='student_details',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.school_details'),
        ),
    ]
