# Generated by Django 3.1.2 on 2020-10-23 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20201023_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='student_eng_admission_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student_details',
            name='student_eng_dob_date',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student_details',
            name='student_nepali_admission_date',
            field=models.CharField(default='2077-07-07', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='student_details',
            name='student_nepali_dob_date',
            field=models.CharField(default='2077-07-07', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='student_fam_occupation',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
