# Generated by Django 3.1.2 on 2020-10-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20201023_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_details',
            name='ethnicity',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], default='1', max_length=9),
        ),
        migrations.AddField(
            model_name='student_details',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female'), ('o', 'Others')], default='1', max_length=9),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='student_nepali_admission_date',
            field=models.CharField(default='2077-07-08', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='student_nepali_dob_date',
            field=models.CharField(default='2077-07-08', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='student_details',
            name='student_photo',
            field=models.ImageField(default='/media/web/', max_length=500, upload_to=''),
        ),
    ]
