# Generated by Django 3.1.1 on 2020-10-04 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20201001_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='stadate',
            new_name='student_admission_date',
        ),
    ]
