# Generated by Django 3.1.2 on 2020-10-16 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20201004_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student_details',
            old_name='username',
            new_name='connect_school',
        ),
    ]
