# Generated by Django 3.1.2 on 2020-10-21 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20201020_0401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_details',
            name='student_admission_date',
        ),
        migrations.RemoveField(
            model_name='student_details',
            name='student_date_of_birth',
        ),
    ]
